system:
  certificateFilePath: "USER_SETTING"
  privateKeyPath: "USER_SETTING"
  rootCaPath: "USER_SETTING"
  rootpath: "USER_SETTING"
  thingName: "USER_SETTING"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.3.0"
    configuration:
      awsRegion: "USER_SETTING"
      iotCredEndpoint: "USER_SETTING"
      iotDataEndpoint: "USER_SETTING"
      iotRoleAlias: "USER_SETTING"
      mqtt:
        port: 443
      greengrassDataPlanePort: 443
